### ISSUE TITLE
Uninitialized variables in unit tests

### ISSUE THREAD

**Issue by combsjy** [tass-belgium/picotcp#319]
In the current v1.6.2 release there are many occurrences of uninitialized stack variables being used.

This results in many of the unit tests "getting lucky".  

I first observed this when trying to build unit tests on an older gcc (v4.4).  Disabling ADDRESS_SANITIZER was required to get the unit tests to build.  But once built some failed.

specifically:
build/test/modunit_mld.elf
build/test/modunit_igmp.elf

These tests failed because they eventually tied to free a stack variable.  This only occurred in tests designed to test failure conditions, that (because of uninitialized stack variables) were not failing and were doing unexpected things.  In one instance pico_mld_process_event was calling a bad address as the result of a p->state value of 120.

Building and running the tests with a more modern compiler with ADDRESS_SANITIZER yielded tests that passed in some circumstances.  If CK_FORK=no was set then some of the unit tests again fail due to uninitialized variable issues.

**Comment by roel0** [comment]
I'm able to reproduce the bug(s).
I will work on a fix this weekend.

**Comment by roel0** [comment]
WIP

FIXED
-------
modunit_mld
modunit_igmp

Still failing with CK_FORK=no
-------
unit_icmp4
unit_dhcp
unit_socket
unit_ipv4
unit_arp

Most bugs are caused by not killing all references to freed buffers or by trying to create links for an address that is already in use, which results in a null pointer link (PICO_ERR_EADDRINUSE)
