### ISSUE TITLE
Add compiler warnings

### ISSUE THREAD

**Issue by toonst** [tass-belgium/picotcp#349]
##### We should add the following warnings:
* GCC & clang compatible warnings:
CFLAGS+= -Wunused-macros
CFLAGS+= -Wvla
CFLAGS+= -Wpedantic

* Clang specific warnings:
CFLAGS+= -Wunreachable-code-return
CFLAGS+= -Wmissing-variable-declarations
CFLAGS+= -Wpointer-bool-conversion
CFLAGS+= -Wunreachable-code-break

##### Still wondering whether these produce false positives or not:
* GCC & clang compatible warnings:
CFLAGS+= -Wswitch-enum
CFLAGS+= -Wcast-align
CFLAGS+= -Wpacked

* Clang specific warnings
CFLAGS+= -Wextra-semi
CFLAGS+= -Wgnu-empty-initializer

**Comment by frederikvs** [comment]
Out of curiosity, how many warnings do these trigger on the current codebase? No need for specifics if you don't have them, just wondering if it's just a handful, or a whole lot of warnings...

**Comment by toonst** [comment]
CFLAGS+= -Wunused-macros --> 59 warnings of unused macros 
CFLAGS+= -Wvla --> 5 warnings, variable length arrays, all in modules/pico_dev_ppp.c
CFLAGS+= -Wpedantic --> 161 warnings, mostly ISO C forbids empty initializer braces in modules/pico_dev_ppp.c

CFLAGS+= -Wunreachable-code-return --> 16 warnings, mostly in stack/pico_socket_multicast.c
CFLAGS+= -Wmissing-variable-declarations --> 75 warnings, mostly globals which should be made static
CFLAGS+= -Wpointer-bool-conversion --> 1 warning

        modules/pico_dhcp_client.c:250:29: warning: address of array 'dhcpc->timer' will always evaluate to 'true' [-Wpointer-bool-conversion]
                if (dhcpc && dhcpc->timer) {
                          ~~ ~~~~~~~^~~~~
CFLAGS+= -Wunreachable-code-break --> 1 warnings

    modules/pico_ipv6.c:790:13: warning: 'break' will never be executed [-Wunreachable-code-break]
                break;
                ^~~~~

**Comment by toonst** [comment]
Would it be a good idea to add compiler specific options in the Makefile this way?

    ifeq ($(CC),clang)
    CFLAGS+= -Wunreachable-code-return
    CFLAGS+= -Wmissing-variable-declarations
    CFLAGS+= -Wpointer-bool-conversion
    CFLAGS+= -Wunreachable-code-break
    endif

**Comment by danielinux** [comment]
I like most of this. My take is:
- -Wunused-macros and -Wunreachable-code-return might not mix well with our current module selection, and may require quite some work to fix, perhaps adding ifdef around macros that would not produce code anyway, or force us to write more complex (!) functions to have reachable code when features that shortcut functions are enabled

- All the others (gcc): definitely in favor, especially because most of them mean better c89 compatibility on all the modules (cc: @mateuszviste) 

- clang-specific: only if we add a clang job in jenkins too (cc: @ISY-Thomas )

**Comment by danielinux** [comment]
I like most of this. My take is:
- -Wunused-macros and -Wunreachable-code-return might not mix well with our current module selection, and may require quite some work to fix, perhaps adding ifdef around macros that would not produce code anyway, or force us to write more complex (!) functions to have reachable code when features that shortcut functions are enabled

- All the others (gcc): definitely in favor, especially because most of them mean better c89 compatibility on all the modules (cc: @mateuszviste) 

- clang-specific: only if we add a clang job in jenkins too (cc: @ISY-Thomas )

**Comment by toonst** [comment]
Added this some time ago now in bab8d1f32f2fe133860ddbb3e152483aa3c5ef99 and 639d5ebdccc93d7948e5d42ed65551340290e981.
