### ISSUE TITLE
mDNS re-init

### ISSUE THREAD

**Issue by frederikvs** [tass-belgium/picotcp#382]
Currently, mDNS does not have any possibility to re-initialise (e.g. after un/replugging the ethernet cable). The call to `pico_socket_bind` fails, since that port is in use.

Probably related to #362 as well. If DHCP would inform mDNS about changed IP, there would be no need for "manual" interaction. But for now, we can get away with just ensuring that a second call to the mdns_init function succeeds, and ask the user to re-init in the DHCP callback.

**Comment by frederikvs** [comment]
@jelledevleeschouwer thanks :-)
Do we have test cases for the re-init as well? To be sure we don't break it again in the future.

**Comment by frederikvs** [comment]
While reviewing your code, I noticed that you made some changes to the timer structures as well. I'm not entirely convinced (yet) that this is the right way to go. I'm not a huge fan of expanding the core code-base to solve a problem in only one module.
(But feel free to try and convince me, if you are sure that this is the best/only way.)

Just thinking out loud here, but since most of the `pico_mdns_timer_add` calls use cookie as a parameter, it might be possible to change something there. E.g. have the cookie track the various timers, and then cancel them (though that might be less efficient, since you're running over the timers multiple times), or just have the cookie keep track of whether it's valid, have the timer functions check that, and if not, just return (though that would mean keeping your cookie in memory for a longer time, and keeping track of when to delete it). 

In `pico_dhcp_client.c` we solved this by keeping track of our timers, and just setting it to canceled.

Or maybe you can think of something even better?

**Comment by jelledevleeschouwer** [comment]
I agree that the way of adding timers isn't that clean, now. 

Indeed, keeping track of the timer in the structure that is passed to the timer-event would do the job like with the DHCP-client. But, we also have to cover the case when no object is passed to the event and, inventing a structure to pass through just to keep track of the timer-ID isn't that elegant IMHO. Neither is it efficient like you mentioned.

The second method with keeping track of the state of the timer again needs a structure where the state has to be kept. This also may result in conflicts in the second session (after re-init) but that's solveable. Also, instead of removal of every element in the tree, the state has to be updated, and this updating depends on the element-type in the tree. In conclusion, this method would result in some overhead per tree per module.

The hashed way provides the most generic and efficient way at the moment. I don't know if every module is "re-initable" at the moment but, if this is supported in more modules in the future, no additional structures have to be invented, no checking has to be performed in the timer-event and no additional routines to update state have to be implemented.

So there are trade-offs to choose between :) It could be that I missed something and that there even a better way, but I'll have to think about that further ;)

**Comment by frederikvs** [comment]
@jelledevleeschouwer did we have a test case on the re-init of mDNS?

**Comment by jelledevleeschouwer** [comment]
I have a test in picoapp, locally. I'll run it again and push it :)

**Comment by frederikvs** [comment]
issue was fixed, and test was added. Closing.
