### ISSUE TITLE
return value of heap_insert

### ISSUE THREAD

**Issue by frederikvs** [tass-belgium/picotcp#387]
similar to #380 the `heap_insert` function has a return value that is currently ignored. This should be easier to fix, since `heap_insert` is currently only used by timers.

**Comment by matthiasvp** [comment]
`heap_insert()` on itself is only used in the pico_timers but those timers are used everywhere and there was/is hardly any checking on the return value of `pico_timer_add(_hashed)()`. Checks have been added but in a lot of cases I only added a debug print saying that the timer could not be set.
This is because there are a lot of functions which do not return anything and which are called periodically through the timer mechanism.(eg: a tick or resource collecting function) They typically are started when a module is initialized.

**Comment by frederikvs** [comment]
Right now, my main concern is that we're not losing memory along the way (e.g. allocate a structure to be used and freed in that timer, then not getting the timer).

Of course, if there's a protocol that completely depends on the periodical timer, we may need to add a mechanism to report that the protocol failed. But (correct me if I'm wrong) I think in most cases it's more like "if you receive this packet, you need to send this message after such time" - if the timer doesn't get set, but a while later memory is available again, the protocol will recover.

**Comment by frederikvs** [comment]
PR #407 solved the immediate issues, and is merged now.
However, the PR didn't include unit tests for the new cases. @ISY-Thomas do you think it's worth the time to test for that sort of thing? It's all code like `if (timer_insert_failed) {return -1;}` or similar, sometimes with a `PICO_FREE` thrown in...

**Comment by frederikvs** [comment]
issue was fixed by #407 . Closing. If @ISY-Thomas thinks we need to add testing for all this, he can re-open.
