### ISSUE TITLE
Upgrade license to GPLv2+ or GPLv3+

### ISSUE THREAD

**Issue by jordens** [tass-belgium/picotcp#408]
Many projects are unable to use picotcp because of the GPLv2-only licensing.
I know there might be a lot of administrative work implied, but upgrading the licensing to something like GPLv2+ would be great. We (https://github.com/m-labs/artiq) could take a serious look at picotcp and I am sure other projects would too. There is a strong need for a solid and well written networking stack with widely applicable and flexible open-source licensing!

https://www.gnu.org/licenses/gpl-faq.html#AllCompatibility

**Comment by hermanius** [comment]
Thank you for your interest in picoTCP.
We are absolutely prepared to evaluate our licensing model if it is in the way of collaborations with other interesting projects like artiq.
We will look into your question and see what can be done. If changing the current licensing model is difficult in the short run we can have a talk about a custom commercial license for your project.
Don't let licensing be in the way to evaluate picoTCP for your project, I'm sure we will find a solution.

**Comment by danielinux** [comment]
Not sure what you mean with "commercial" license, but a proprietary license won't be an option if the project to link with is GPLv3. 

In my personal opinion, it's not a bad idea to upgrade to GPLv2+, as other v3 projects might benefit from the possibility to link picoTCP, while existing GPLv2 derivatives would still be possible.

On the other hand, I don't think that switching to GPLv3 would be a good idea at all.

**Comment by frederikvs** [comment]
This has been asked in person a number of times, but then usually slips under the radar after a short while, because we're focussing on technical issues. Thanks for bringing it up again @jordens .

I agree with @danielinux that going GPLv3 only (or GPLv3+) would not be a good idea. There are too many situations in embedded where you explicitly need to lock down the device. If everybody could go around reflashing their electricity meters with their own firmware, power companies would be in huge trouble. 

Going GPLv2+ however is an option worth considering. It leaves open the options that GPLv2 gave, but also opens up options for GPLv3.
Now as you may know there is also a commercial entity behind this project, so we'll need to consider whether switching would have any impact on our business model. I doubt it, but it needs to be considered in depth. We'll talk to the business people and report back.

**Comment by maximevince** [comment]
I think GPLv2+ would be a sensible choice, too.

Op zo 4 sep. 2016 om 10:30 schreef Frederik Van Slycken <
notifications@github.com>:

**Comment by hermanius** [comment]
Thanks all for the input. We will evaluate internally and decide shortly on how to continue.

**Comment by phalox** [comment]
One more topic I'd like to check here: Licensing GPLv2+ would mean that you release your code under any future GPL license. If for some reason we don't like GPLv5, how do we approach that?

I see one way, which is to license picoTCP under both GPLv2 and GPLv3. That should probably cover most of the use cases.

Any input on this?

**Comment by danielinux** [comment]
@phalox I like your forward thinking even more than the GPL2+ pick. In fact, you should not trust any third party (even if it is FSF) about future modifications of the license which have not been taken into account by the copyright holders. The license might then look like this:

> This software is distributed under the terms of GNU GPL as released by FSF, either version 2 or (at your option) version 3. 

as opposed to the classic GPL2+:

> This software is distributed under the terms of GNU GPL as released by FSF, either version 2 or (at your option) any later version. 

Keep up the good work, and thanks for listening to the needs of the community. We are all looking forward to a license upgrade which could result in a better inclusion of the increasing amount of potential GPL3 derivatives.

**Comment by hermanius** [comment]
Actually, the idea to possibly migrate to a dual GPLv2 and GPLv3 license is coming from Frederik.
Does anyone know of a project that uses this?

Best regards,

Herman.

**Comment by jordens** [comment]
Thanks a lot for the discussion and the open and pragmatic approach!

The big problem I see with "GPLv2-or-3" is that it still restricts other projects that want to use picotcp: when combined with another project that is GPLv3+ (e.g. artiq), the result is  GPLv3-only, immediately cutting off the "+" from that other project's license.

Obviously, this is all irrelevant if there never is a GPLv4 or if you (the picotcp developers and tass-belgium) turn out to be open to relicensing to GPLv2-3-4 when the time comes.

But IANAL and I might be wrong.

**Comment by frederikvs** [comment]
If ever there is a GPLv4, we'll consider it, and if we approve of it, we'll update the license again.

The only difficulty is that other projects will need to ask their developers to release all their own code under "GPLv3 or later", while the resulting project (as a combination of "3 or later" and "2 and 3 only" code) must be considered GPLv3 only. 
If a project does not ask their developers to release under the "or later" version, they might end up with parts of their code that they can not upgrade to later versions, even though picoTCP may then decide to upgrade. However, it's clear that the project as a whole can't be "or later", since it includes our code which is "only".

Ah, the joys of licensing and minor paranoia :-)

BTW, @jordens, you mention artiq is GPLv3+, but at the bottom of the github page it only mentions "Licensed under GNU GPL version 3" - you might want to check whether that's correct, and fix it.

**Comment by danielinux** [comment]
@jordens : not an actual problem indeed. A potential GPLv4 compatibility issue (if ever!) would raise only towards GPLv4-only projects (i.e. not 2+ or 3+). I understand the doubts raised towards the v2+, it's not a good idea to commit on a license that we haven't read yet (because it hasn't been redacted either), it sounds like signing a blank contract. Even if we (the community) trust FSF, this is a commercial project and Altran (the copyright holder) needs to protect themselves from potential bureaucratic pitfalls, which might be introduced by the license in their business model later on.

Anyway, that will hopefully be an equally interesting argument when you work on a GPLv4-only project in a few years, and still want to integrate picoTCP :)

**Comment by phalox** [comment]
@jordens Could you double check on the artiq license? I've been going through the website, articles and repo and I only see GPLv3.

We're still in the process of validating this change internally, but we'll keep you posted!

**Comment by jordens** [comment]
@frederikvs, @phalox  artiq is GPLv3+. I updated the README.
@danielinux It will be an actual problem. Not only for GPLv4 projects but for GPLv2+ and GPLv3+ projects as well because it will -- at least until picotcp relicenses -- prevent distributing the bundle under any of licenses that the + refers to other than v2 and v3, i.e. GPLv4.

**Comment by frederikvs** [comment]
The decision has been made : from now on we'll release under both GPLv2 and GPLv3. We still need to make it official and all, and we'll announce it with the next release (which I hope to create after merging in some open pull requests), but I already wanted to give you all the heads-up.

As was mentioned here before, we didn't go to a full GPLv2+, because we don't know what the FSF is planning, nor do we know how the FSF itself will evolve. (Will its point of view become more extreme open-source, or will some other people take control who are against openness?)
If/When a GPLv4 is released, we will review it, and if it doesn't interfere with our objectives, we will update the licensing again - our CLA gives us the freedom to do this.

This does mean that for now any resulting binary can only be released under 2 and 3, not the "or later" option. However, my advice would be for open-source projects that link to us to release their source code under the "or later" option, so that if/when the time comes and we add the GPLv4 option, that the resulting binaries become 2/3/4.

disclaimer : IANAL, don't consider this to be valid legal advice.

**Comment by jordens** [comment]
Thanks!
