### ISSUE TITLE
warnings in unit tests

### ISSUE THREAD

**Issue by laurensmiers** [tass-belgium/picotcp#419]
There are a bunch of warnings in the unit tests. This is cumbersome when making new unit tests and seeing if you have any warnings, ... etc
I made a separate branch for this [warnings_unit_tests](https://github.com/tass-belgium/picotcp/tree/warnings_unit_tests) where the warnings are gone and altered a few things that should definitely be reviewed. f.e. the pico_dns_notation_to_name and pico_dns_name_to_dns_notation where a function parameter was changed to provide consistency with the internal pico_dns_strlen().

I know there has been some discussion already if we want to have zero-warnings unit tests.
I believe we should, if we make our stack warning free, we should do the same to the unit tests.

Main reason why we would want this is because the warnings hide bugs (mostly of wrong types and callbacks, etc.) in the unit tests. f.e. [1](https://github.com/tass-belgium/picotcp/blob/development/test/unit/modunit_pico_mld.c#L480), [2](https://github.com/tass-belgium/picotcp/blob/development/test/unit/modunit_pico_igmp.c#L21), [3](https://github.com/tass-belgium/picotcp/blob/development/test/unit/modunit_pico_dns_client.c#L19).

If we want to go further with this, I still have a few questions about the unit tests but I first want to see if we are going through with this.

**Comment by frederikvs** [comment]
Warnings in the unit tests : It's not something I consider high priority, and I won't allocate much time to it. There's also no need to put the unit tests through all the same warning flags we put the stack itself through.
But for the warnings we do have enabled, I agree it would be nicer if we were warning free for them. If you're willing to put some time in to clean it all up, we can ask @ISY-Thomas to put it into jenkins, and then everybody has to keep it clean :-)

Looking briefly at your branch, I notice a bunch of replaces of `unsigned int` to `uint16_t` (in some dns stuff). Are those in internal functions or in API functions? Because I think we had a rule somewhere that API functions are the only ones that get to use the "old" stuff like `unsigned int`.

Other than that, a quick overview, I like your work. If you're willing to put it into a PR, I'll review it properly and merge it in :-)

**Comment by laurensmiers** [comment]
Thanks for reviewing Frederik. As you stated, I now realize it would have been better to make a PR, sorry for that :). I'll make a PR for this and move the discussion to the PR.

**Comment by laurensmiers** [comment]
@ISY-Thomas , would it be possible to check the warnings in the Jenkins? Just to ensure we don't have to start cleaning up in a few months :).

**Comment by ISY-Thomas** [comment]
@laurensmiers So what you want is a job which checks/counts the compilerwarnings for this branch? (and later Dev)

**Comment by laurensmiers** [comment]
@ISY-Thomas The branch is already merged into development, but yeah a job which checks/counts the warnings for the unit tests.

**Comment by ISY-Thomas** [comment]
@laurensmiers Here you go: http://jenkins.picotcp.com:8080/job/picoTCP_Dev/job/PicoTCP_dev_Units_WarningCount/

Currently it is red when any warning is present. I'll have this run at every commit from now on, but let's make sure that we start off green first?!  ;-)

**Comment by laurensmiers** [comment]
Great, Thanks :+1: 
Damn, those warnings snuck by me last time. Should be OK now
