### ISSUE TITLE
how to develop a tun2socks

### ISSUE THREAD

**Issue by whisper-bye** [tass-belgium/picotcp#430]
Is it possible to develop a tun2socks by using picotcp?
I wish to use it instead of lwip, see [badvpn/tun2socks](https://github.com/ambrop72/badvpn/tree/master/tun2socks)
thx!

**Comment by frederikvs** [comment]
I'm not sure what tun2socks does exactly, could you elaborate on that a bit?

What I can tell you right now, is that currently we have no SOCKS implementation, though I see no reason this couldn't be developed :-)

**Comment by whisper-bye** [comment]
tun2socks just like the tun/tap driver, IP packets -> lwip -> tcp connection

Tun2socks network-layer proxifier

The tun2socks program "socksifes" TCP connections at the network layer. It implements a TUN device which accepts all incoming TCP connections (regardless of destination IP), and forwards the connections through a SOCKS server. This allows you to forward all connections through SOCKS, without any need for application support. It can be used, for example, to forward connections through a remote SSH server.

I wish to use picotcp instead of lwip

**Comment by danielinux** [comment]
This should be doable. PicoTCP already has a tap device driver (no need to create the tap with an external program) and could be used to intercept the TCP connections as you described with a few tweaks. Program's main loop should expect data from either side (socks connection/picotcp accepted TCP socket) and forward to the opposite side.

The tap driver has to be modified a bit so that you can intercept SYN segments from your program, to initiate your sock conversation while the stack is receiving the connection.

The hard part would be to "convince" picoTCP to accept all the connection on one of its listening sockets, as the stack is strict about matching the destination addresses and ports. 

One solution could be to add the destination IP to the picoTCP interface, and create a listening socket to the destination port. This way picoTCP thinks it is the endpoint of the incoming connection, and responds accordingly. This is possibly very simple, but you need to take care about the resources allocated (each connection potentially creates a new socket and adds an IP address to picoTCP network configuration), e.g. with a garbage collector or by actively cleaning up the resources allocated at the end of the connection.

A more difficult solution would be to hack the internals of picoTCP to accept all the connection locally, thus bypassing IP and port checking. If you want to go through this path, here are a few pointers:
- Look into `pico_ipv4_process_local_unicast_in` in `modules/pico_ipv4.c`:`pico_ipv4_process_in` and `pico_transport_receive` call in `pico_ipv6_process_in` to alter the condition to accept packets from ipv4/ipv6 to the transport layer. 
- Find a way to hardcode your single listening socket through the path `pico_socket_deliver`->`pico_socket_transport_deliver`->`socket_tcp_deliver_ipv4`|`socket_tcp_deliver_ipv6`
- Once the new socket has been spawned, ensure that the return path can be realized (and overwrite src port and address for downlink traffic).

It sounds fun, I hope you consider doing this. If it comes up properly designed I'd use it regularly.

**Comment by whisper-bye** [comment]
@danielinux 
thanks for your reply, it is very interesting for me, I'm going to try to do it.
