### ISSUE TITLE
Can't compile under macOS

### ISSUE THREAD

**Issue by mhagmajer** [tass-belgium/picotcp#461]
```
du: illegal option -- b
usage: du [-H | -L | -P] [-a | -s | -d depth] [-c] [-h | -k | -m | -g] [-x] [-I mask] [file ...]
-e 	[LIBSIZE] 
size: Unknown command line argument '-t'.  Try: '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/size -help'
size: Did you mean '-A'?
-e 
```

**Comment by phalox** [comment]
@frederikvs can you have a look? :) Also, if @basilfx has some time, would be great too!

**Comment by frederikvs** [comment]
Thanks for the reminder!

The problem isn't so much that it can't compile under MacOS (I compile under MacOS all the time), but rather that some of the statistics we like to print out are incorrect (since they rely on GNU tools, not whatever is bundled with MacOS).

So you can actually proceed with the library that was built.

That being said, I agree it would be much nicer if we didn't get these error outputs on MacOS :-)
