### ISSUE TITLE
problem with ethernet HUB

### ISSUE THREAD

**Issue by quangde** [tass-belgium/picotcp#469]
Hello all,

I have very stupid issue and I don't know why???
I ported picoTCP on STM32F4 and it works. Now I want to monitor the data exchange between Master(Server) and Slave (Client), thus I'm using simple HUB. The problem is: when the STM32F4 is plugged in ethernet HUB, I can not ping it from PC. I tried with Ethernet Router or direct with PC, it works again.
I know that I received the data from HUB, but it seems the sending back has problem because HUB can not forward them to PC.
Did somebody have same problem?
Thank you and have nice day.

**Comment by frederikvs** [comment]
I think this is the first I've heard of this kind of problem. To my knowledge, actual hubs are becoming rare things, and usually are quite old hardware, so a first question would be : are you sure that your hub is still working properly?

A simple first test could be to just attach multiple PCs to the hub, see if you can ping in all directions.

If that doesn't solve it, and if you have a serial output on your STM32F4 board, another way to go about finding the root cause would be to get a packet dump. I would suggest modifying your ethernet driver so that it prints a hexdump-like output of each packet to the serial line. Then capture that output, perhaps filter it with grep or similar tools (so that you only have the packets, no other output), and convert it to wireshark format (`text2pcap` can help here). 
When you have that, I would advise you to take a dump on both ends of the connection (once with the serial dump described above, once simply wireshark on your PC), and try the ping again.

If there's any weirdness in the packets coming out of picoTCP, wireshark will probably flag this already. If there's nothing suspicious, compare the two dumps : are there packets that appear in the one dump, but not the other?

Please let us know if this helps in finding the cause of the problem. If you don't find it yourself, maybe share the two wireshark files (as well as other debug output from picoTCP), so we can investigate further :-)

**Comment by quangde** [comment]
Thank Frederikvs for your quick response.
I can not do anything till Tuesday because of holiday. I would like to look at back to hardware schematic, maybe the TX/RX pin with cross-over cable. it means:  the RX+- are compatible with the cable, but the TX+- are not. Thus, the board can receive but sending has problem. 
Anyway, I will keep you update.
