### ISSUE TITLE
pico_ipv4_route_add() is not correctly adding the gateway

### ISSUE THREAD

**Issue by yogk** [tass-belgium/picotcp#496]
Hi,

I am able to connect to a device which is on the same network as picoTCP i.e. PicoTCP tap0 is having the ip "192.168.82.106" while the device I connect to has ip "192.168.82.108". Netmask is "255.255.255.0". This works fine.

However I need to connect PicoTCP to another server with an ip "51.142.X.Y" through a gateway "192.168.82.1".  Hence I added 

    `  pico_string_to_ipv4("51.142.x.y", &dst.addr);
       pico_string_to_ipv4("255.255.255.0", &netmask.addr);
       pico_string_to_ipv4("192.168.82.1", &gateway.addr);
       route = pico_ipv4_route_add(dst,netmask,gateway,1, link);
       printf("route added =%d\n", route);                  ====> prints 0 which is success.

       gateway = pico_ipv4_route_get_gateway(&dst);
       printf("gateway address dst =%u\n",gateway.addr)   =====> prints also 0 and not 192.168.82.1

`

I think PicoTCP is not connecting to this server at all  as gateway added is never used and is always using gateway addr "0" which is incorrect.

Please let me know what is wrong here and how to connect to the server using PicoTCP.

note: I can connect to the server 51.142.x.y from my machine running linux  (without PicoTCP) which means there is no problem of firewall etc. 

Regards
Yogesh

**Comment by frederikvs** [comment]
@yogk I'm sorry I don't have time to go very deep in helping you debug these issues.

2 quick thoughts though : 

```
  pico_string_to_ipv4("51.142.x.y", &dst.addr);
  pico_string_to_ipv4("255.255.255.0", &netmask.addr);
```
* I think you need the netmask to be the mask of the target IP range, not of the local network. So that would be `255.255.0.0` in the case of `51.142.x.y`. 
* I'm not sure how picoTCP responds to letters in the IP address. Perhaps it handles it without issue, but I'd suggest you change the target to `51.142.0.0` :-)
